name: IaC - All

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Target environment: dev, test, prod'     
        required: true
        default: 'dev'  

jobs:

  build-and-deploy:
  
    runs-on: ubuntu-latest
    
    steps:
    
      # Checkout code
    - uses: actions/checkout@master

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webAppName=kmg88devops-${{ github.event.inputs.targetEnv }}"


