name: mkdir example

on:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create dir
        run: mkdir mydirname

      - name: Change dir
        run: ls -la mydirname
          
      - name: pwd dir
        run: ls
