name: mkdir example

on:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create dir
        run: |
          mkdir mydirname
          cd mydirname
          ls
